import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";


export const metadata = {
  title: "Tirth Ghumo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={"antialiased bg-[#FFF9EE]"}
      >
        {children}
      </body>
    </html>
  );
}
